### ISSUE TITLE
Error on loading data_samples when using open_weather_models_2D_parameters

### ISSUE THREAD

**Issue by louis49** [meteofrance/meteonet#11]
DatasetBuildError: multiple values for unique key, try re-open the file with one of:
    filter_by_keys={'stepType': 1}
    filter_by_keys={'stepType': 0}

**Comment by larvorg** [comment]
Hello,

could give me more details about your error message ? It happens when you want to load the dataset ? If yes, for which file ?

**Comment by louis49** [comment]
Yes exactly, this one by ex. meteonet-master/data_samples/weather_models/arome_2m_NW_20180501000000.grib

Try with Jupiter notebook notebooks/weather_models/open_weather_models_2D_parameters.ipynb
at line data = xr.open_dataset(fname, engine='cfgrib') 

<img width="1015" alt="Capture d’écran 2020-04-08 à 14 08 50" src="https://user-images.githubusercontent.com/357595/78782596-89b19180-79a2-11ea-8543-3a26bedfd2a1.png">
<img width="1005" alt="Capture d’écran 2020-04-08 à 14 08 35" src="https://user-images.githubusercontent.com/357595/78782586-86b6a100-79a2-11ea-8c99-0f7c8ba6352e.png">

**Comment by larvorg** [comment]
Did you test with another GRIB file from meteonet ? It is working for me with this GRIB file. The error seems to come from the cfgrib library. What is your version of cfgrib ? I have the version 0.9.8.1

**Comment by larvorg** [comment]
We remark they can exist compatibility problems between some librairies according to versions : eccodes, cfgrib,..
You can find in attachment a zipped yaml file containing the configuration of my anaconda virtual environment.
You can easily create exactly that environment on your PC with this command line : 
> conda env create -f local_env.yml 
[local_env.zip](https://github.com/meteofrance/meteonet/files/4482509/local_env.zip)
