### ISSUE TITLE
Radar coordinates

### ISSUE THREAD

**Issue by mbtgy** [meteofrance/meteonet#12]
I couldn't find the information in the documentation, so: do the radar rainfall coordinates correspond to the center of the pixels, or one of the corners?

**Comment by larvorg** [comment]
Hello,

the radar coordinates (about rainfall and reflectivity) correspond to the top left of each pixel.

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).

**Comment by larvorg** [comment]
The update is now performed : the radar coordinates (about rainfall and reflectivity) correspond now to the center of each pixel (and not anymore the top left corner of each pixel).
