### ISSUE TITLE
NW data missing in ground_stations

### ISSUE THREAD

**Issue by GabrielGodefroy** [meteofrance/meteonet#15]
Hi meteonet teams,

Really good job and initiative, thank you.

For now, the _groundstations_ folder only seems to contain the data for the SE of France.
Are you planning on releasing the dataset for the NW data as well?

Thanks in advance,
G.

**Comment by larvorg** [comment]
Hi,

you talk about the ground stations data sample of the Github project ? If it is the case, we just put some samples as examples on this Github project.

If you want to access to all data, here is this link : https://meteonet.umr-cnrm.fr/dataset/
We put also a part of the dataset on Kaggle (NW zone) with challenges and the same toolbox of the Github project : https://www.kaggle.com/katerpillar/meteonet. 

Gwennaëlle
