### ISSUE TITLE
Page to download meteonet toolbox not found 

### ISSUE THREAD

**Issue by naomichx** [meteofrance/meteonet#17]
Hi ! I would like to use the meteonet database and toolbox, however I can't download the toolbox, the page is not found when I go to the link. Do you have another way for downloading it ?

Thanks in advance !

**Comment by larvorg** [comment]
Hi!

what is the link you tested? Actually, you post that issue on the github project of the toolbox, so you are in the good place!
The link of our website refers to our toolbox which is a github project : https://github.com/meteofrance/meteonet

You can clone that project on your computer by executing this command line : git clone https://github.com/meteofrance/meteonet.git
You can also visit our Kaggle page (https://www.kaggle.com/katerpillar/meteonet). We put some of the data and the associated toolbox (Python notebooks). You can use directly  that scripts and data on your Kaggle workspace.

**Comment by takaomoriyama** [comment]
@naomichx If you are trying to open the link https://meteofrance.github.io/meteonet/install/ in the Installing the toolbox section in https://github.com/meteofrance/meteonet, I would suggest to access https://github.com/meteofrance/meteonet/blob/master/docs_src/english/install.md instead.

**Comment by larvorg** [comment]
Hello,

I fix the link issue : I put this link (https://meteofrance.github.io/meteonet/english/install/), which is a nicer version of the link you precise (https://github.com/meteofrance/meteonet/blob/master/docs_src/english/install.md).
