### ISSUE TITLE
Data for other regions (SW and NE)

### ISSUE THREAD

**Issue by adrienpellissier** [meteofrance/meteonet#18]
Hello MeteoNet team, 
Thanks for the datasets already existing, great job! 

I wanted to know if you plan to release also data for South West and North East part of France, especially for the ground stations data.

Thanks in advance,

**Comment by larvorg** [comment]
Hello, 

it is not planned in a near future. MeteoNet has been designed to train AI models and benchmark them with a reasonable baseline dataset in size. So everyone can work with it, even if a personal computer for example. 

In the long run, we think about other larger datasets, with other objectives:
- provide a fuller dataset in space and time to perform finetuning before deployment in production
- an other dataset with climatology data, so the time series would be longer 
- ...etc
