### ISSUE TITLE
Starting notebook fails with FileNotFoundError

### ISSUE THREAD

**Issue by mrechte** [meteofrance/meteonet#3]
Hello,
I installed, using virtualenv and PIP.
Starting open_ground_stations.ipynb, I have the following error:

```
(METEONET) [rechtem@diabolik-arch meteonet]$ ipython notebooks/ground_stations/open_ground_stations.ipynb 
/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py:935: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
2020-02-26 08:21:15,930  - WARNING - User is not known. If you experiment some problems with path for library please add the specific path in `user_configuration.py` module
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/python/METEONET/meteonet/notebooks/ground_stations/open_ground_stations.ipynb in <module>
      1 zone, date, param = 'SE', '20160101', 'hu'
      2 fname = "../../data_samples/ground_stations/%s_20160101.csv"%zone
----> 3 df = pd.read_csv(fname,parse_dates=[4],infer_datetime_format=True)
...

FileNotFoundError: [Errno 2] File ../../data_samples/ground_stations/SE_20160101.csv does not exist: '../../data_samples/ground_stations/SE_20160101.csv'
```
However, this file exists:

```
(METEONET) [rechtem@diabolik-arch meteonet]$ ls -l data_samples/ground_stations/SE_20160101.csv 
-rw-r--r-- 1 rechtem rechtem 7679526 25 févr. 16:45 data_samples/ground_stations/SE_20160101.csv
```
On the other hand, moving first to the notebook directory, and starting from there gives:

```
(METEONET) [rechtem@diabolik-arch meteonet]$ cd notebooks/ground_stations/
(METEONET) [rechtem@diabolik-arch ground_stations]$ ipython open_ground_stations.ipynb 
/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py:935: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/python/METEONET/meteonet/notebooks/ground_stations/open_ground_stations.ipynb in <module>
      1 #from data_exploration.utils.user_configuration import *
----> 2 from meteonet_toolbox.user_configuration import *

ModuleNotFoundError: No module named 'meteonet_toolbox'

```
I tried installing ipython in the virtualenv, but it gives the same error.
Thanks

**Comment by LBerth** [comment]
Hi mrechte,
I've tried fixing the ModuleNotFound error, can you try again when moving first to the notebook directory ?

**Comment by mrechte** [comment]
Hello Lea,
So far so good, but there is still a missing dependency:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/python/METEONET/lib/python3.8/site-packages/IPython/core/interactiveshell.py in get_cells()
   2776             """generator for sequence of code blocks to run"""
   2777             if fname.endswith('.ipynb'):
-> 2778                 from nbformat import read
   2779                 nb = read(fname, as_version=4)
   2780                 if not nb.cells:

ModuleNotFoundError: No module named 'nbformat'
/home/rechtem/python/METEONET/lib/python3.8/site-packages/IPython/core/interactiveshell.py:2801: UserWarning: Unknown failure executing file: </home/rechtem/python/METEONET/meteonet/notebooks/ground_stations/open_ground_stations.ipynb>
  warn('Unknown failure executing file: <%s>' % fname)

```
Thanks

**Comment by LBerth** [comment]
Hi Marc,
Can you try installing notebook with "conda install -c conda-forge notebook" or "pip install notebook" ?
Then run "jupyter notebook" in the repository. Then you should be able to navigate with jupyter and open the notebooks.
I've also added this installation in the documentation.

**Comment by mrechte** [comment]
I installed nbformat (pip install nbformat), but still got the initial error. So I edited open_ground_stations.ipynb (line 75), removing the ../../ prefix. I then moved the git home, and run:
`$ ipython notebooks/ground_stations/open_ground_stations.ipynb`
I was faced with another problem: tkinter is required and was not installed on my machine.
Eventually I got a nice plot. Is that what I am supposed to get ?
![Capture d’écran de 2020-02-27 13-37-05](https://user-images.githubusercontent.com/5902317/75445768-5b35a500-5966-11ea-85a4-b4fff557add7.png)

**Comment by LBerth** [comment]
Almost : you should try opening the notebook with the command `jupyter notebook` instead of `ipython notebooks/ground_stations/open_ground_stations.ipynb`. Then you would see the explanations and different steps to open the data and plot the figure, and it should also solve the FileNotFound issue.

![notebook](https://user-images.githubusercontent.com/19271957/75456008-45ca7600-597a-11ea-82dc-80a2d9dcd860.png)

**Comment by mrechte** [comment]
To reach that point, I had to install jupyter in the virtualenv (which is not in the requirements.txt), because the system-wide installed jupyter was running outside the virtualenv and therfore was not seeing the installed requirements...
The notebook executed until "Plot with Cartopy", but cartopy is a missing import.
Pip install cartopy failed with a gcc compilation error. I open a separate issue for that point.
Thank you Léa.
