### ISSUE TITLE
Why no data for all region?

### ISSUE THREAD

**Issue by vk496** [meteofrance/meteonet#7]
The data is for a "NW" and  "SE" quarters. Would be possible to have all the data?

**Comment by LBerth** [comment]
Hi ! We chose these 2 subregions for reasons of disk usage (the dataset is already 170Go for only 2 quarters of France). But many users are asking for the other quarters, so we will try to upload them in a future version of the dataset.

**Comment by vk496** [comment]
Cool, thnks
